### ISSUE TITLE
Date profile for citations and media objects

### ISSUE THREAD

**Issue by DavidMStraub** [gramps-project/web-api#108]
Citations and media objects have a `date` key, but we do not currently return a formatted date. I suggest to add a `profile` key for those endpoints containing the formatted date to start with.

**Comment by cdhorn** [comment]
It seems every object will need a profile for one reason or another.

Does that suggest the design is wrong being so tightly bound to the schema and we should step back and reconsider anything?

**Comment by DavidMStraub** [comment]
> Does that suggest the design is wrong being so tightly bound to the schema and we should step back and reconsider anything?

Not necessarily. I'm currently implementing all the object list and details views in the JS frontend. For this purpose, the "raw" objects are not so useful and it's really the information in the "profile" that I need, which is why I am now doing a "to do list" of things to add to the profile that I need for the web app.

But in principle it's also possible that there are use cases for the API that make direct use of the raw objects. This could e.g. be apps that implement more logic themselves. So I think our current architecure of having a raw object with an optional "profile" with more pre-processed/formatted information is actually quite nice because it is very flexible.

**Comment by DavidMStraub** [comment]
Fixed by #119!
