### ISSUE TITLE
Search index w/o private records

### ISSUE THREAD

**Issue by DavidMStraub** [gramps-project/web-api#111]
As discussed in #95, in order to prevent search hits from showing up when searching for keywords that only appear in private attribiutes, we need a separate search index for public-only text strings.

**Comment by cdhorn** [comment]
Not familiar with how Whoosh works, just curious no way to structure the current engine schema to handle that?  If not we should make it configurable I think.

Some stats from a copy of my own tree so you have some context for that question:

[2020-12-08 07:06:45,256] INFO in app: Building search index ...
[2020-12-08 07:12:49,347] INFO in app: Done building search index.

-rw-rw-r--. 1 webapi webapi 431154262 Dec  8 07:12 MAIN_07z3dvknwoyunann.seg

With something this size searches are still usually blazing fast unless you wild card too broadly.  I ran some on things like Mar* and they took a bit over a minute to complete.

**Comment by DavidMStraub** [comment]
Yes, good point. For the huge majority of objects, there won't be any private attributes so it is inefficient to duplicate everything.
