### ISSUE TITLE
Tests fail - new webargs version?

### ISSUE THREAD

**Issue by DavidMStraub** [gramps-project/web-api#120]
In the latest commits, some tests fail. This might be due to the new webargs version: [changelog](https://webargs.readthedocs.io/en/latest/changelog.html).

**Comment by cdhorn** [comment]
Dropped support for Python 3.5. You still want to keep 3.5 compatability?

**Comment by cdhorn** [comment]
Note test_users.py was failing for me in master prior to this.

**Comment by DavidMStraub** [comment]
> Dropped support for Python 3.5. You still want to keep 3.5 compatability?

Oh. Hadn't noticed this.

Since 3.5 has reached EOL, I've seen many projects dropping support for it. Since we have much more dependencies than Gramps core, for me it would make sense to drop 3.5 compatibility for the API even if Gramps 5.2 will support it.

**Comment by cdhorn** [comment]
Yeah I agree.
