### ISSUE TITLE
Add /people/{}/timeline and /families/{}/timeline support

### ISSUE THREAD

**Issue by cdhorn** [gramps-project/web-api#123]
I propose adding support for timelines to the people and families endpoints.   This differs from the events list in that it would include optional events for spouses, parents, children, and siblings. 

A returned timeline event would consist of the event type, description, date, place name, latitude, longitude, age of the person at time of the event.  Some optional attributes might be number of citations supporting the event, highest citation confidence rating, and links to media objects associated with the event. 

The idea is to assemble and provide all the information needed to construct a timeline view of a person in a manner similar to that supported by the FamilySearch timeline feature but perhaps with some additional options and information.

**Comment by DavidMStraub** [comment]
Neat idea!

I'm wondering what the best way would be to additionally enable a map view of this timeline. In order not to have to fetch all existing places, I suppose the best method at present would be to fetch the events in the timeline, extract the Gramps IDs, and then fetch `places` with an `or` rule using `HasIdOf:<gramps_id>`?

**Comment by cdhorn** [comment]
We have place handle in the event, it's one iteration away.  I have not looked closely at places, if that has no lat/long do you need to start walking up the heirarchy and if so should I take it that far?

I am thinking probably find a way to let you combine the timelines from multiple people as well.

Have you used FamilySearch before? It is free, if not you should register for an account and take a look at the timeline view for a person in the tree there, they really did a nice job with it.

**Comment by DavidMStraub** [comment]
> We have place handle in the event, it's one iteration away. I have not looked closely at places, if that has no lat/long do you need to start walking up the heirarchy and if so should I take it that far?

I don't think you need to implement that in the backend, I was just wondering what would be the most efficient way to fetch this additional info in a second API call. Fetching multiple objects with a single call, given their handles, is possible only using filter rules, right?

> Have you used FamilySearch before? It is free, if not you should register for an account and take a look at the timeline view for a person in the tree there, they really did a nice job with it.

I should try it out to get inspiration, true. I have only seen screenshots so far.

**Comment by cdhorn** [comment]
I just checked, the HasIdOf rule only accepts a single argument. So you would need to string a bunch of them together. I am not sure how that one works on the backend, I suspect it still iterates over all the objects looking for matches.

I know it seemed redundant with handle= so we ditched it, but it might make sense to add handles= query parm to the collection endpoints so you could pass it a comma delimited list to fetch multiples in one shot. It might also make sense to extend gramps_id in the same manner and call it gramps_ids=

For timelines I have a prototype working, it returns person and place profiles with the event data at the moment. There are still numerous issues with it though I am trying to sort through.

**Comment by DavidMStraub** [comment]
> I just checked, the HasIdOf rule only accepts a single argument. So you would need to string a bunch of them together. I am not sure how that one works on the backend, I suspect it still iterates over all the objects looking for matches.

Yes, that's the way I'm doing it [at the moment](https://github.com/DavidMStraub/Gramps.js/blob/a10ae8f33858b41370b82246efe71eb77db1210a/src/views/GrampsjsViewSourceCitations.js#L24-L29).

> I know it seemed redundant with handle= so we ditched it, but it might make sense to add handles= query parm to the collection endpoints so you could pass it a comma delimited list to fetch multiples in one shot. It might also make sense to extend gramps_id in the same manner and call it gramps_ids=

Yes indeed that might be good.

> For timelines I have a prototype working, it returns person and place profiles with the event data at the moment. There are still numerous issues with it though I am trying to sort through.

Cool, looking forward to it.
