### ISSUE TITLE
Media file and thumbnail endpoints

### ISSUE THREAD

**Issue by DavidMStraub** [gramps-project/web-api#13]

**Comment by DavidMStraub** [comment]
So far, we have
- `/media/<string:handle>` for the media object
- `/media/` for a collection of media objects

I would add
- `/media/<string:handle>/file` for the file
- `/media/<string:handle>/thumbnail/<width:int>/<height:int>` for a thumbnail fitting into width/height
- `/media/<string:handle>/cropped/<x1:int>/<y1:int>/<x2:int>/<y2:int>` for a cropped image
- `/media/<string:handle>/cropped/<x1:int>/<y1:int>/<x2:int>/<y2:int>/thumbnail/<width:int>/<height:int>` for the thumbnail of a cropped image

The `cropped` endpoints would return an error for non-image mimetypes.

**Comment by Nick-Hall** [comment]
Could we use something like `/people/<string:handle>/media/cropped` to return all the images for a person cropped according to the rectangles in the MediaRef objects?

**Comment by cdhorn** [comment]
That seems like it would be useful for all the objects with media references.

**Comment by DavidMStraub** [comment]
But we can't return a *list* of images unless we return a JSON with a base64-encoded image. For the image endpoints, I was envisaging directly returning the correct mime type. (This is also how I handled it at my current web app implementation.)

Having endpoints for the actual images/files rather than their base64-encoded data also has a huge practical performace advantage: namely, you can optionally implement those endpoints as 301 redirects and have the file serving handled by a web server rather than the Python backend, which is much more performant and scalable. For instance, I use this in my current web app implementation by optionally hosting the files on S3 and the endpoints returning 301 redirects to private S3 URLs.

**Comment by DavidMStraub** [comment]
... but this might be a good application of the HATEOAS pattern [metioned here](https://github.com/gramps-project/web-api/issues/17#issuecomment-711036474): we could add a dictionary with the *image URLs* to the person (and all other object) endpoints:

```
{
  ...,
  {'images': {
    'cropped': [
      '/media/handle/cropped/1/2/3/4',
      ...
    ],
  }
}
```

**Comment by cdhorn** [comment]
> But we can't return a list of images unless we return a JSON with a base64-encoded image.

> ... but this might be a good application of the HATEOAS pattern

Yes, I see what you mean.

> you can optionally implement those endpoints as 301 redirects and have the file serving handled by a web server rather than the Python backend, which is much more performant and scalable. For instance, I use this in my current web app implementation by optionally hosting the files on S3 and the endpoints returning 301 redirects to private S3 URLs.

I see the advantage here performance wise. But how are the media items then secured if you do not want to make them public, or some subset can be viewable by one group of users but not another?

**Comment by DavidMStraub** [comment]
> I see the advantage here performance wise. But how are the media items then secured if you do not want to make them public, or some subset can be viewable by one group of users but not another?

- On S3 e.g. by using a signed URL
- On files served by the Python backend by using the token in the query key (in this case admittedly there is no performance gain as the file still needs to be served by the backend, but it is much easier to use a URL e.g. in a web app in an `img` tag than using a data URL which contains the entire image as a bas64-encoded string)

**Comment by Nick-Hall** [comment]
> `/media/<string:handle>/thumbnail/<width:int>/<height:int>` for a thumbnail fitting into width/height

Gramps caches two sizes of thumbnail: Normal and Large.  Have a look at the [thumbnail](https://github.com/gramps-project/gramps/blob/master/gramps/gen/utils/thumbnails.py#L81) code.  The scaling is defined in the [constants](https://github.com/gramps-project/gramps/blob/master/gramps/gen/const.py#L257).

Using the default sizes would avoid calling the thumbnailer every time.  The sizes are useful for the GUI but may not be sufficient for web apps.

**Comment by Nick-Hall** [comment]
Have you seen the [Photo Tagging](https://gramps-project.org/wiki/index.php/Photo_Tagging_Gramplet) gramplet?

Regions for people are defined the media reference objects.  Perhaps an API call could return all the media references in the backlinks for a media object?  Do we have an endpoint for backlinks yet?

**Comment by DavidMStraub** [comment]
> Gramps caches two sizes of thumbnail: Normal and Large. Have a look at the thumbnail code. The scaling is defined in the constants.
Using the default sizes would avoid calling the thumbnailer every time. The sizes are useful for the GUI but may not be sufficient for web apps.

I don't think we can use the Gramps thumbnailer as it depends on GTK. But I also don't see a reason to - any app using the API (e.g. a web app) might have completely different requirements for thumbnails (sizes, caching, ...) compared to Gramps desktop. I was planning to copy over a cleaned-up version of my [implementation at the existing web app](https://github.com/DavidMStraub/gramps-webapp/blob/master/gramps_webapp/image.py). For instance, its frontend makes use of responsive images, which requires having two thumbnails, one with twice the size, served on devices with retina display.

> Have you seen the Photo Tagging gramplet?

My web app already implements this, not too different from narrative web. Screenshot:

<img width="632" alt="image" src="https://user-images.githubusercontent.com/10965193/97090972-96dd5780-1638-11eb-8694-5ef437b2730d.png">

> Regions for people are defined the media reference objects. Perhaps an API call could return all the media references in the backlinks for a media object? Do we have an endpoint for backlinks yet?

So what we have is that the media references for non-media objects are returned at the respective endpoints, e.g. `/api/person/somehandle`:

```
{...,  "media_list": [{"rect": [51, 19, 59, 33], "ref": "238CGQ939HG18SS5MG"}, ...]}
```
but we don't have a backlink yet, in the sense of getting all rectangles defined for a given image. Is that what you mean? I agree we need this. My implementation above actually cheats because the frontend fetches *all* people and media objects and then filters in Javascript.

I guess to do this we would have to use `find_backlink_ref`, right? But if we do this for any object (let's say, always have an additional key `backlinks: [...]`), that would probably slow things down a lot, since it would have to essentially search the entire database for every object.

Perhaps we can enable the `backlink` key for any object with an additional boolean query parameter? E.g. `/api/media/somehandle/?backlink=1` to fetch all the info needed to build the above tagged photo?
