### ISSUE TITLE
Exception: no such database backend: 'sqlite'

### ISSUE THREAD

**Issue by DavidMStraub** [gramps-project/web-api#2]
The Travis builds still fail with the above exception stemming from the call `make_database("sqlite")`. 

https://travis-ci.com/github/gramps-project/web-api/jobs/384394846#L309

On my local system it works, even in a virtual environment, so I'm a bit puzzled how to debug this. I also tried [registering the plugins](https://github.com/gramps-project/web-api/commit/0aed5fc78c9ee74573c61f94c18a0038aad7df85) but this did not fix it.

@Nick-Hall, do you know what the cause could be?

**Comment by Nick-Hall** [comment]
Yes.  When you change the major version you will also have to update the target version for the plugins.  For example, the [`gramps_target_version`](https://github.com/gramps-project/gramps/blob/master/gramps/plugins/db/dbapi/sqlite.gpr.py#L30) for the sqlite plugin will need to be set to `'5.2'`.

I'll have a look at the procedure we used for the last major release.

**Comment by DavidMStraub** [comment]
But this pipeline failed already before I changed the version from 5.1.4 to 5.2.0, so I think there must be a different cause.

**Comment by DavidMStraub** [comment]
Apologies, I realized the offending call (`make_database`) wasn't actually used, so I simply fixed it by removing it.
