### ISSUE TITLE
Notes HTML output

### ISSUE THREAD

**Issue by DavidMStraub** [gramps-project/web-api#26]
Add HTML output for notes. This can be based on https://github.com/DavidMStraub/gramps-webapp/blob/master/gramps_webapp/gramps.py#L531-L580, but support for internal links needs to be added.

Still to be decided how that fits into the API.

**Comment by DavidMStraub** [comment]
I suggest to add a `format=` URL argument. This would allow implementing multiple formats. The current format could be called `raw` or something, then other formats could be added as `format=html` etc.

For internal links, that are represented in the DB as `gramps://...`, it would be great if the user could define the way they are converted to actual URLs, such as [the `build_link` method](https://github.com/gramps-project/gramps/blob/c567b9e399514cfbf3bc6e5dd3996a04b7f2ed97/gramps/plugins/webreport/narrativeweb.py#L1395). But doing this with a query parameter is tricky, given the many different possibilities. Maybe we could assume that a given app always builds links using handles *or* Gramps IDs, but not both. Then we could simply add a query parameter `use_grampsid_in_links` (or something like that), which would convert all `gramps://object_class/handle/some-handle` to `gramps://object_class/gramps_id/some-grampsid`. Then it would be fairly easy for a client to do the remaining conversion (e.g replace the string `gramps://person` by `https://my-app/people/detail`).

**Comment by cdhorn** [comment]
I agree format= should be the keyword.  Thinking about it, why not allow it to consume a comma delimited list of values and allowing some limited form of jinja2 style templating in it? I'm thinking of something along these lines:

format=html,href["http://my-app/people/detail/{{ grampsid }}"],options=["target=_blank"],text["{{ name_given }} {{ name_surname }}"]

**Comment by DavidMStraub** [comment]
I'm wondering where to define the `format` keyword; at the moment, all children of `GrampsObject(s)Resource` have the same query arguments, but `format` would only make sense on `/note` I guess. Or would `format` on a person endpoint (for instance) also trigger showing a formatted note when using `extend=note_list`?

**Comment by DavidMStraub** [comment]
(although I wouldn't know how to do that, as currently have no way of extending objects within `"extended"`, and I doubt we want to go there...)

**Comment by DavidMStraub** [comment]
After some more thought, I suspect the best way is to promote the schema in `@use_args` to a class attribute of `GrampsObjectResource`, which allows to extend it in subclasses, e.g.

```python
class NoteResource(GrampsObjectProtectedResource, NoteResourceHelper):
    GET_ARGS = GrampsObjectResource.GET_ARGS.copy()
    GET_ARGS["format"] = fields.Str(...)

**Comment by DavidMStraub** [comment]
Turned out that idea didn't work as the decorator cannot access `self`. Will continue discussion in the PR.

**Comment by Nick-Hall** [comment]
> For internal links, that are represented in the DB as gramps://..., it would be great if the user could define the way they are converted to actual URLs, such as the build_link method.

The original idea was that an external application would define a custom protocol.  A simple implementation would just redirect to an http request.
