### ISSUE TITLE
Finish unit tests for people and people/{handle} endpoints

### ISSUE THREAD

**Issue by cdhorn** [gramps-project/web-api#34]
Unit tests for filter, rules, strip, keys, skipkeys, profile, and extend options.

**Comment by cdhorn** [comment]
@DavidMStraub @Nick-Hall I didn't open a pull request yet obviously, but I pushed a commit for the unit-tests branch I've been playing with to my fork a short while ago.

If you could please take a glance over it with regards to the approach I am taking with the test_endpoints subpackage and let me know if it seems okay or you see any major structural or other issues with it. I've not done something like this before, want to make sure I'm on the right track and any advice or pointers are greatly appreciated.

Note you will see some minor changes in emit.py based on the schema tests to normalize some things, please let me know if those are agreeable as well as they exclude or recast some values.

I was thinking of converting the apispec over to OpenAPI 3.0, that would be a different PR at some point. Any objection to me opening an issue and doing so?  I was not sure if 2.0 was picked for a specific reason.

Thanks!

**Comment by DavidMStraub** [comment]
Hi,

I just had a very quick look and I think the approach is looking very good. Did the unit tests with the example DB work for you?

Concerning OpenAPI 2.0 vs. 3.0: if I'm not mistaken, Swagger doesn't support 3.0, that was my main reason to choose 2.0.

**Comment by cdhorn** [comment]
Yes all the unit tests in there work, the exampledb is working out very nicely!  I do wish it had data to exercise every possible feature/option but there is more than enough there.  

I was going to feed the unit-tests upstream a major object at a time but it seems to make more sense to just finish them all up and submit one large PR with the whole subpackage.  I know you don't like those but it is pretty self contained other than some of the minor fixes for things it has helped uncover so far.  Thoughts?

The swagger.io editor supports conversion from 2.0 to 3.0 as well as editing 3.0.

**Comment by DavidMStraub** [comment]
Sure, go with the big PR :+1:

> The swagger.io editor supports conversion from 2.0 to 3.0 as well as editing 3.0.

For some reason I thought that https://generator.swagger.io/ didn't support displaying 3.0, but if that's the case, great!
https://generator.swagger.io/

**Comment by cdhorn** [comment]
> Sure, go with the big PR +1

Thanks, that does seem to make the most sense for this.

> For some reason I thought that https://generator.swagger.io/ didn't support displaying 3.0, but if that's the case, great!

Ah, I've never played with that, so many toys so little time!  I've only made use of the swagger editor https://editor.swagger.io/
