### ISSUE TITLE
Unit tests for metadata/summary, metadata/researcher, metadata/surnames

### ISSUE THREAD

**Issue by cdhorn** [gramps-project/web-api#48]

**Comment by romjerome** [comment]
Nice project!

Note, maybe you could also include something for formats (name and place)?
and database creation?

Based on [Gramps XML namespaces-like](https://raw.githubusercontent.com/gramps-project/addons-source/master/lxml/xpaths_4_2_x.txt):

```
/database/header
/database/header/created
/database/header/created/@date
/database/header/created/@version
...

/database/name-formats
/database/name-formats/format[0]
/database/name-formats/format[0]/@number
/database/name-formats/format[0]/@name
/database/name-formats/format[0]/@fmt_str
/database/name-formats/format[0]/@active
...
/database/namemaps
/database/namemaps/map[0]
/database/namemaps/map[0]/@type
/database/namemaps/map[0]/@key
/database/namemaps/map[0]/@value
```
As well as '[preferences.place-format](https://github.com/gramps-project/gramps/blob/master/gramps/gen/config.py#L254)' key?

**Comment by DavidMStraub** [comment]
@romjerome, the `/metadata` endpoint is meant for information about the currently loaded database. Is that what you mean? Can you please have a look at the current API specification and then suggest more concreteley how to improve it (which endpoints with which payload)? Please feel free to open a new issue with a feature suggestion.

**Comment by cdhorn** [comment]
About metadata, I am now thinking perhaps things exposed there ought to be read only.  

In which case researcher and types maybe should be separate endpoints. I had types separate at one point and probably should have left it that way.  Any thoughts on this?
