### ISSUE TITLE
Backlinks

### ISSUE THREAD

**Issue by DavidMStraub** [gramps-project/web-api#52]
This is to continue the discussion of backlinks started in #13.

Backlinks (i.e. finding objects referencing a given object) are useful for finding objects that reference a media object, but also much more generally.

So the question is how we implement those in the API.

As far as I can see, DBAPI implements `get_backlink_handle` by a SQL lookup of the `references` table, where both the referring and the referred handles are indexed in the default SQLite implementation, which is great, so this should be very fast.

I see the following options:

1. Always add all backlinks to all object endpoints (in spite of the above, this might lead to a slowdown - we would need to check)
2. Add a boolean query switch `backlinks` to enable backlinks on all object endpoints.
3. Add a `backlink` endpoint do fetch backlinks of a specific object.

In the case of 2., the backlinks of a given media object would be obtained by
`/api/media/myhandle/?backlink=1`
and looking for the "backlink" key.
In the case of 3. by
`/api/media/backlinks/myhandle`

**Comment by cdhorn** [comment]
I think case 2, it can be enabled on /api/media and /api/media/{handle}. I agree a separate "backlinks" keyword in the base response is good. 

I think case 3 is not clean as that position in the path is for {handle} which can have any value.  You could do /api/media/{handle}/backlinks though. But I think 2 is more flexible if you enable it on both endpoints as the code will be there anyway.

**Comment by DavidMStraub** [comment]
In progress at #55.

**Comment by cdhorn** [comment]
PR #55 merged, closing issue
