### ISSUE TITLE
Break types out into /api/types/default and /api/types/custom

### ISSUE THREAD

**Issue by cdhorn** [gramps-project/web-api#62]
@DavidMStraub initially we had a separate /api/types and then moved it to /api/metadata but I think I'd like to move it back to /api/types.  It just seems more "right", I don't know how to explain it. In doing so I also want to break it up so we have /api/types/default and /api/types/custom so under /api/types/default we can also expose the numeric values associated with them.

I'm looking over the relationship calculator and endpoint and I didn't really understand it at first and left most of the functionality out.  So I want to refactor that and develop the tests for it as I do so. There are some types in there for siblings and partners that I think maybe should be exposed. So if you are okay with this proposed change I will work on /api/types to get that sorted and then move onto the relationship endpoint work. Let me know your thoughts.

**Comment by DavidMStraub** [comment]
Sounds good. The types are stored in `metadata` in the table, but this does not mean it is logical from an API user point of view (types are not really metadata).

Not sure what you mean by the relationship stuff since I've never dived that deep into this kind of functionality, but sure, go ahead :rocket:

**Comment by Nick-Hall** [comment]
Yes.  The `metadata` table has been used to store things that aren't metadata.

@cdhorn I agree that your initial instinct seems correct.  I almost mentioned it before.
