### ISSUE TITLE
Add /api/reports endpoint

### ISSUE THREAD

**Issue by cdhorn** [gramps-project/web-api#67]
Expose the reports plugin API.

**Comment by cdhorn** [comment]
So far I have code working to fetch all the report attributes and available options, or those for a specific report.  It is similar in that regard to what I did for /api/filters.

I'm thinking of something similar for running them as well, passing structured json with the options in it like I did for the rules= parm to build a filter on the fly. That seems reasonable but wanted to see if there were other ideas...

**Comment by DavidMStraub** [comment]
Yes sounds good, another option would be to use GET to fetch the available options and then use POST to generate the report; after all, it creates a new object (the downloadable file). Not sure if this is the RESTful way to do it.

**Comment by cdhorn** [comment]
Yeah my thinking was for any file generated to be transitory in nature and cleaned up immediately afterwards if possible.

**Comment by cdhorn** [comment]
So I now seem to have this working with a /api/reports/{reportid}/file endpoint. It accepts the report options in an options= query parm in json format, uses them to generate the report, reads it into a buffer for send_file, and then deletes it before returning.

We could have a /api/reports/{reportid}/save that does the same but saves it locally with a supplied file name but I'm not sure it is really needed. Any thoughts?
