### ISSUE TITLE
Add /api/config endpoint?

### ISSUE THREAD

**Issue by cdhorn** [gramps-project/web-api#69]
I'm actually not sure about this one, and I see it as pretty low priority.  

But does it make sense to expose the config options API or not?  Would a web front end possibly want to make use of some of them, like the behavior ones?  I have not looked closely enough, would a web front end maybe even want to store options in it?

**Comment by DavidMStraub** [comment]
Yes, good question, my tendency is to say there is no need for it, as this will essentially a server configuration which should be done using the `gramps` executable before actually starting the server.

A web frontend would certainly not use it for configuration, as that configuration would be user dependent and is better saved in the browser.

**Comment by Nick-Hall** [comment]
The colours used in some reports may be stored in the configuration file.

**Comment by cdhorn** [comment]
They appear to use report path in there as well. Closing this for now, we can always revisit it if a use case arises that needs it.

**Comment by DavidMStraub** [comment]
> we can always revisit it if a use case arises that needs it.

I found a use case :slightly_smiling_face: https://github.com/gramps-project/Gramps.js/issues/76

New issue #294, PR #295.
