### ISSUE TITLE
Profile without families

### ISSUE THREAD

**Issue by DavidMStraub** [gramps-project/web-api#71]
As mentioned in #70, the `profile` option for people leads to long computation time when `include_families` is switched on in the relevant method, so I think we have to provide a way to disable it, but still keep the profile for names & events.

Possibilities I can think off:

- Treat `profile` like `extend`: `profile=name,families,events`, `profile=all`
- New endpoints: `/api/people/profile`, `/api/people/handle/profile` showing only the profile and with query config options

Opinions?

**Comment by cdhorn** [comment]
I would lean toward treating it like extend.  I had given thought to that before but didn't do it.

**Comment by cdhorn** [comment]
Reason for that is /api/people/profile isn't valid as that position in the path is for {handle}

**Comment by cdhorn** [comment]
Not sure I'd call this an enhancement so much as a performance fix. 

Can you add a few additional labels?  "performance" and "quality assurance" are the two that come to mind.

**Comment by cdhorn** [comment]
I took a pass at this and then realized it will conflict with the backlinks.  Is that ready to merge yet?

**Comment by DavidMStraub** [comment]
I will add the missing API docs now, sorry for the delay.
