### ISSUE TITLE
Get default locale

### ISSUE THREAD

**Issue by DavidMStraub** [gramps-project/web-api#73]
The `/translations/somelocale` endpoint is really useful to translate e.g. a web app frontend, however I realized that it is not possible at present to get the default language/locale of the Gramps instance, only the list of available languages. Since currently the default locale is also used in the translation of dates (see #56), I think it would make sense to add the possibility to get the default language and to use this for translating strings.

However, I am not sure what the best location would be for this information. Perhaps changing the `/api/translations` endpoint to

```
{'available': [...], 'default': {'isocode': 'en', ...}}
```

**Comment by cdhorn** [comment]
A couple thoughts...

I have an updated metadata I was playing with and actually put it in there.  But it could be put under here. 

A stupid question probably but is that something that can be changed after Gramps is instantiated?  Maybe /api/locale endpoint to get and set it?

Also I had not realized/known when I last touched this that in the apispec additionalProperties is used to model dictionaries. The returned list of translations was initially a dictionary and I changed it but think it is more natural to change it back. I can submit a PR to do that if you agree, that was a mistake on my part.

**Comment by DavidMStraub** [comment]
> I have an updated metadata I was playing with and actually put it in there. But it could be put under here.

Metadata would be perfectly fine.

> A stupid question probably but is that something that can be changed after Gramps is instantiated? Maybe /api/locale endpoint to get and set it?

I wouldn't recommend it as this will affect all users. I think it's better to keep it as part of the server configuration and to use the `/translation/...` and `?locale=...` options for user-dependent language config.

> Also I had not realized/known when I last touched this that in the apispec additionalProperties is used to model dictionaries. The returned list of translations was initially a dictionary and I changed it but think it is more natural to change it back. I can submit a PR to do that if you agree, that was a mistake on my part.

Yes, sounds good.

**Comment by cdhorn** [comment]
Thinking about it, locale really doesn't have to do with Gramps or the database, so I am thinking a /api/locale may make sense from that point of view. Thoughts?  If okay I'll submit a PR for that and fixup translations in the same.

**Comment by Nick-Hall** [comment]
You can't change the default locale, but it is possible to run reports in different languages.  We use deferred translation to implement this.

**Comment by cdhorn** [comment]
Question too about this.  As I understand is "lang" is the ISO code.  I referred to it as isocode in translations endpoint. Is it more proper to refer to it that way or as lang?

**Comment by cdhorn** [comment]
/api/metadata now contains locale/lang as per PR #76
