### ISSUE TITLE
Full text search

### ISSUE THREAD

**Issue by DavidMStraub** [gramps-project/web-api#74]
From the app point of view, a really great feature would be a Google-style full text search where I can just search for an arbitrary word and I get a list of all person, place, note, ..., objects that contain it. The API to implement that would be quite obvious,

```
/api/search/?query=something
```

and it would return a dictionary with lists of objects,
```
{
  'people':  [...],
  'notes': [...],
}
```

In order not to have to read the entire database on every search query, such a feature would require an index. Fortunately, there are excellent Python-only indexers, e.g. [whoosh](https://whoosh.readthedocs.io/en/latest/index.html). Building the index might take a couple of seconds, but updating it would be very fast as we can leverage the `change` timestamp field in the database.

If this works and turns out to be useful, it might even be something that finds its way into the Gramps desktop app ...

**Comment by Nick-Hall** [comment]
I assume that this would use the [`matches_string`](https://github.com/gramps-project/gramps/blob/master/gramps/gen/lib/baseobj.py#L59), [`matches_regexp`](https://github.com/gramps-project/gramps/blob/master/gramps/gen/lib/baseobj.py#L91) and associated methods.

**Comment by DavidMStraub** [comment]
> I assume that this would use the [`matches_string`](https://github.com/gramps-project/gramps/blob/master/gramps/gen/lib/baseobj.py#L59), [`matches_regexp`](https://github.com/gramps-project/gramps/blob/master/gramps/gen/lib/baseobj.py#L91) and associated methods.

If we use an indexing library, we don't need that since the matching is done on the index (by the indexing library), not on the database or Gramps objects.

If we would instead search all existing objects directly, we could use these methods, but I'm sure this will be too slow for big databases (especially in a web context where people are nowadays used to search results popping up before they finished typing).

**Comment by Nick-Hall** [comment]
I was thinking that we could simply build an [inverted index](https://en.wikipedia.org/wiki/Inverted_index) in Gramps.  The [`get_text_data_list`](https://github.com/gramps-project/gramps/blob/master/gramps/gen/lib/baseobj.py#L119) method already defined which fields should be considered as text.

**Comment by DavidMStraub** [comment]
Cool, I was not aware of this function! I think that's exactly what is needed as input to an indexer like whoosh, so combining the two it should be fairly easy to implement. I will play around.

**Comment by DavidMStraub** [comment]
It works! I'm having fun and will submit a draft PR so you see where I'm going.
