### ISSUE TITLE
License preamble

### ISSUE THREAD

**Issue by cdhorn** [gramps-project/web-api#75]
@DavidMStraub @Nick-Hall Should we be including the license preamble and exclusion of warranty in the header for every source file and likely our copyright as well?  I notice Gramps follows that practice. Or is it deemed sufficient to have the LICENSE file in the package?

**Comment by Nick-Hall** [comment]
Yes.  We should follow the recommendation in the appendix of the [license](https://github.com/gramps-project/gramps/blob/master/COPYING#L282).  Each file should contain the preamble and copyright lines.  See the main Gramps repository for examples.

**Comment by cdhorn** [comment]
@DavidMStraub a PR to fix this will touch everything. Unsure if you want to put it together or if I should try to.  

May I propose as part of it that the files in resources for the major objects that are singular be renamed to match the plural endpoints? person.py -> people.py and so forth?

**Comment by DavidMStraub** [comment]
I'm fine with both changes (and happy if I don't have to do it :wink:).

**Comment by DavidMStraub** [comment]
Solved by #81.
