### ISSUE TITLE
Problems with metadata

### ISSUE THREAD

**Issue by DavidMStraub** [gramps-project/web-api#84]
I am having problems with the new metadata endpoint related to localization.

- The keys `Family Tree` and `Database` that are used in `family_tree_summary` are localized, but the English values are hard-coded. We need to use `gettext` to translate them or the dictionary will look up will fail, causing an `UnboundLocalError` below.
- The keys that are just converted to snake case (`number_of_places`) are also localized, so they end up as `anzahl_der_orte` etc. in my case. This is not good as we need those to be constant.

**Comment by DavidMStraub** [comment]
@cdhorn I took the liberty of assigning the issue to you as you :slightly_smiling_face:

**Comment by cdhorn** [comment]
Sure, I will take a look at it. Sorry if I didn't realize that.

**Comment by DavidMStraub** [comment]
Fixed by #86 :tada:
