### ISSUE TITLE
Hide all private records on per-request basis

### ISSUE THREAD

**Issue by DavidMStraub** [gramps-project/web-api#95]
This is one of the most important missing features in my opinion: we need to add the possibility to only return non-private information on all endpoints. This can later (= soon) be enabled/disabled on a per-user basis depending on permissions (#15) but for now we can just treat it as a global option, too.

In my old backend, I solved this by simply [returning a `PrivateProxyDb`](https://github.com/DavidMStraub/gramps-webapp/blob/master/gramps_webapp/db.py#L52-L56) instead of the actual database in each request (this would be `get_dbstate` in our case). That's clean and very easy to implement. However, since the proxy DB only overloads a subset of the underlying DB's mathods ([see source](https://github.com/gramps-project/gramps/blob/master/gramps/gen/proxy/private.py)), I suspect we are currently using other, low-level, methods which return private data even when used on the `PrivateProxyDb`. So we need to carefully check all our code for such cases, find ways to make it safe, and add tests to make sure we don't leak private info.

Please feel free to use this thread to post any observations/checks you have made.

**Comment by DavidMStraub** [comment]
Observation: the full-text search index contains the textual representation of all objects. Even if the search endpoint can make sure to only return objects that are not private, the textual representation can definitely contain private information. We can solve this by storing the full and the "stripped" textual representation in the index and returning the appropriate results at the search endpoint.

**Comment by cdhorn** [comment]
The exporters make use of that and the other proxies in addition to filters. The thought occurred to me it might be needed elsewhere and might not cover all cases.

Stepping back, some part of me wonders if this is really the responsibility of the consuming application and not the API and whether we are not clearly delineating between the two.  

As I understand things, which may not be correct, your web front end is really a single application instance multi-user use case. As you have full control of the application the above argument could apply.

But I also recognize you would clearly want the access control in the API for a distributed multi-user use case where you do not control the application only the data presentation.  I guess this is how you are looking at things.

I still think, BTW, we need to support database management and import functionality for single user use cases with configuration options to enable/disable it when not being used in that manner.

**Comment by DavidMStraub** [comment]
List of Db methods we use:

```python
db.method("get_%s_from_handle", gramps_class_name)
db.method("iter_%s_handles", gramps_class_name)
db.method("get_%s_from_gramps_id", gramps_class_name)
db.get_bookmarks()
db.get_family_bookmarks()
db.get_media_bookmarks()
db.get_event_bookmarks()
db.get_citation_bookmarks()
db.get_note_bookmarks()
db.get_place_bookmarks()
db.get_source_bookmarks()
db.get_repo_bookmarks()
db.get_event_from_handle(handle)
db.get_person_from_gramps_id(gramps_id)
db.get_person_from_handle(handle)
db.get_place_from_handle(handle)
db.get_family_from_handle(handle)
db.get_source_from_handle(handle)
db.get_citation_from_handle(handle)
db.get_media_from_handle(handle)
db.get_note_from_handle(handle)
db.get_repository_from_handle(handle)
db.get_tag_from_handle(handle)
db.find_backlink_handles(handle)
db.get_dbname()
db.get_dbid()
db.get_default_handle()
db.get_number_of_people()
db.get_number_of_families()
db.get_number_of_sources()
db.get_number_of_citations()
db.get_number_of_events()
db.get_number_of_media()
db.get_number_of_places()
db.get_number_of_repositories()
db.get_number_of_notes()
db.get_number_of_tags()
db.get_researcher()
db.get_surname_list()
db.get_summary()
db.name_formats
db.get_name_group_mapping(surname)
db.get_name_group_keys()
db.get_event_attribute_types()
db.get_event_types()
db.get_person_attribute_types()
db.get_family_attribute_types()
db.get_media_attribute_types()
db.get_family_relation_types()
db.get_child_reference_types()
db.get_event_roles()
db.get_name_types()
db.get_origin_types()
db.get_repository_types()
db.get_note_types()
db.get_source_attribute_types()
db.get_source_media_types()
db.get_url_types()
db.get_place_types()
db.get_mediapath()
```

**Comment by DavidMStraub** [comment]
> As I understand things, which may not be correct, your web front end is really a single application instance multi-user use case. As you have full control of the application the above argument could apply.

You can think  of the application as simply a presentation layer, it cannot do anything about security/data access. For instance, the JS web app runs entirely in the user's browser. Setting a flag `private_only=True` on the API calls doesn't help at all, since it's trivial for a malicious user to change it. So this has to be taken care of by the backend/API.

More concretely, eventually the API will be able to hand out tokens with different scopes: tokens that only allow reading data, tokens that also allow adding/modifying data, and tokens that only allow reading non-private data.

**Comment by cdhorn** [comment]
Ahh that clicks now, I see what you mean.

So non-private is one subset but do we not also want to be able to restrict someone to say non-living people or only specific lineages?

**Comment by DavidMStraub** [comment]
> So non-private is one subset but do we not also want to be able to restrict someone to say non-living people or only specific lineages?

In principle that would be great, but when I tried this in the "old" app, it didn't really work: For instance, I used `LivingProxyDb` to only show data from deceased people, but when iterating over media objects, it still showed me the wedding photos, along with descriptions and all, from living people.

So the conclusion I arrived at back then was that `private` is the only thing that can be relied upon for security, since it is part of the database.

**Comment by DavidMStraub** [comment]
(So what I would do in practice would be to mark all data, including media, from living people as private using some of the tools in Gramps.)

**Comment by DavidMStraub** [comment]
Did some more investigation on the methods, using `inspect`:


### Methods of `PrivateProxyDb` (should be safe)

```
get_event_from_handle
get_person_from_gramps_id
get_person_from_handle
get_place_from_handle
get_family_from_handle
get_source_from_handle
get_citation_from_handle
get_media_from_handle
get_note_from_handle
get_repository_from_handle
find_backlink_handles
get_default_handle
```

### Inherited from `ProxyDbBase` (probably safe?)

```
get_bookmarks
get_family_bookmarks
get_media_bookmarks
get_event_bookmarks
get_citation_bookmarks
get_note_bookmarks
get_place_bookmarks
get_source_bookmarks
get_repo_bookmarks
get_tag_from_handle
get_dbid
get_number_of_people
get_number_of_families
get_number_of_sources
get_number_of_citations
get_number_of_events
get_number_of_media
get_number_of_places
get_number_of_repositories
get_number_of_notes
get_number_of_tags
get_researcher
get_name_group_mapping
get_name_group_keys
get_event_attribute_types
get_event_types
get_person_attribute_types
get_family_attribute_types
get_media_attribute_types
get_family_relation_types
get_child_reference_types
get_event_roles
get_name_types
get_origin_types
get_repository_types
get_note_types
get_source_attribute_types
get_source_media_types
get_url_types
get_mediapath
```

### Inherited from `DbReadBase` or `DbGeneric` (need to check if safe)

```
method
get_dbname
get_surname_list
get_summary
name_formats
get_place_types
```

**Comment by DavidMStraub** [comment]
### Inherited from `DbReadBase` or `DbGeneric` (need to check if safe)

- `method`: this is just a shorthand which eventually only calls the `iter_...` and `get_...` methods that are either defined in `ProxyDbBase` or `PrivateProxyDb` - so should be safe
- `get_dbname`: the DB name can never be private
- `get_surname_list`: looks to me like this doesn't respect privacy. **Is this a problem? Not sure.**
- `name_formats`: same as previous I guess
- `get_summary`: apparently does not respect privacy. **I don't see it as security problem, but might be easy to implement for ProxyDb**?
- `get_place_types`: no privacy concerns
```

**Comment by DavidMStraub** [comment]
The following objects are not filtered (`ProxyDbBase` forwards them to the underlying DB instance):

- name groups
- types of all kind
- bookmarks
- tags

To me, none of those seem sensitive.

So it seems this issue is mostly a non-issue. Which is good!
